import Head from 'next/head'
import About from '../components/About'

import Main from '../components/Main'
import NavBar from '../components/NavBar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Arnaldo Neto | Desenvolvedor Front-End</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Main />
      <About />
    </div>
  )
}
